# Generated by Django 4.2 on 2024-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CityList', '0004_alter_city_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='walk_score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
